package LDF

var OperationType = map[uint8]string{
	1: "LOP_FORMAT_PAGE",
	2: "LOP_INSERT_ROW", 3: "LOP_DELETE_ROW",
	4: "LOP_MODIFY_ROW", 5: "LOP_MODIFY_HEADER", 6: "LOP_MODIFY_COLUMN",
	7: "LOP_SET_BITS", 9: "LOP_DELTA_SYSIND", 10: "LOP_SET_FREE_SPACE", 11: "LOP_DELETE_SPLIT",
	12: "LOP_UNDO_DELETE_SPLIT", 13: "LOP_EXPUNGE_ROWS", 16: "LOP_FILE_HDR_MODIFY",
	17: "LOP_SET_GAM_BITS",
	22: "LOP_INSYSXACT", 128: "LOP_BEGIN_XACT", 129: "LOP_COMMIT_XACT",
	130: "LOP_ABORT_XACT", 131: "LOP_PREP_XACT", 132: "LOP_MARK_SAVEPOINT ",
	133: "LOP_FORGET_XACT", 134: "LOP_CREATE_FILE", 135: "LOP_DROP_FILE",
	136: "LOP_MARK_DDL", 140: "LOP_HOBT_DELTA", 141: "LOP_LOCK_XACT", 150: "LOP_BEGIN_CKPT",
	152: "LOP_XACT_CKPT", 153: "LOP_END_CKPT", 154: "LOP_BUF_WRITE", 155: "LOP_IDENTITY_TYPE",
	160: "LOP_BEGIN_RECOVERY", 161: "LOP_END_RECOVERY", 162: "LOP_NONLOGGED_OP",
	170: "LOP_SORT_BEGIN", 171: "LOP_SORT_END", 172: "LOP_SORT_EXTENT",
	173: "LOP_CREATE_INDEX", 174: "LOP_DROP_INDEX", 175: "LOP_SORT_MEMORY",
	200: "LOP_REPL_COMMAND", 201: "LOP_BEGIN_UPDATE", 202: "LOP_END_UPDATE",
	203: "LOP_TEXT_POINTER", 204: "LOP_TEXT_INFO_BEGIN", 205: "LOP_TEXT_INFO_END",
	206: "LOP_REPL_NOOP", 207: "LOP_TEXT_VALUE", 211: "LOP_SHINK_NOOP",
}

var ContextType = map[uint8]string{
	0: "LCX_NULL", 1: "LCX_HEAP", 2: "LCX_CLUSTERED",
	3: "LCX_INDEX_LEAF", 4: "LCX_INDEX_INTERIOR", 8: "LCX_GAM",
	10: "LCX_IAM", 11: "LCX_PFS", 23: "LCX_BOOT_PAGE_CKPT",
}
