package LDF

var OperationType = map[uint8]string{
	0: "LOP_NULL",
	1: "LOP_FORMAT_PAGE",
	2: "LOP_INSERT_ROW", 3: "LOP_DELETE_ROW",
	4: "LOP_MODIFY_ROW", 5: "LOP_MODIFY_HEADER", 6: "LOP_MODIFY_COLUMN",
	7: "LOP_SET_BITS", 9: "LOP_DELTA_SYSIND", 10: "LOP_SET_FREE_SPACE", 11: "LOP_DELETE_SPLIT",
	12: "LOP_UNDO_DELETE_SPLIT", 13: "LOP_EXPUNGE_ROWS", 15: "LOP_FORMAT_PAGE",
	16: "LOP_FILE_HDR_MODIFY",
	17: "LOP_SET_GAM_BITS", 18: "LOP_COUNT_DELTA", 19: "LOP_ROOT_CHANGE",
	20: "LOP_MARK_SAVEPOINT", 21: "LOP_INSERT_SPLIT",
	22: "LOP_INSYSXACT", 23: "LOP_DELETE_INDEX", 24: "LOP_INSERT_INDEX",

	25: "LOP_MODIFY_INDEX", 26: "LOP_DELETE_LEAF", 27: "LOP_INSERT_LEAF",
	28: "LOP_MODIFY_LEAF", 29: "LOP_DELETE_INTERNAL", 30: "LOP_INSERT_INTERNAL", 31: "LOP_MODIFY_INTERNAL",
	32: "LOP_DELETE_BLOB",
	33: "LOP_INSERT_BLOB", 34: "LOP_MODIFY_BLOB", 35: "LOP_DELETE_TEXT",
	36: "LOP_COMPACT_SLOT", 37: "LOP_DELETE_ROWS_VERSION",
	38: "LOP_INSERT_TEXT", 39: "LOP_MODIFY_TEXT",
	40: "LOP_DELETE_XML", 41: "LOP_INSERT_XML", 42: "LOP_MODIFY_XML",
	43: "LOP_DELETE_FILESTREAM", 44: "LOP_INSERT_FILESTREAM", 45: "LOP_MODIFY_FILESTREAM",
	128: "LOP_BEGIN_XACT", 129: "LOP_COMMIT_XACT",
	130: "LOP_ABORT_XACT", 131: "LOP_PREP_XACT", 132: "LOP_MARK_SAVEPOINT ",
	133: "LOP_FORGET_XACT", 134: "LOP_CREATE_FILE", 135: "LOP_DROP_FILE",
	136: "LOP_MARK_DDL", 137: "LOP_HOBT_DDL",
	140: "LOP_HOBT_DELTA", 141: "LOP_LOCK_XACT",
	146: "LOP_MODIFY_STREAMFILE_HDR",
	148: "LOP_BP_DBVER", 150: "LOP_BEGIN_CKPT",
	152: "LOP_XACT_CKPT", 153: "LOP_END_CKPT", 154: "LOP_BUF_WRITE", 155: "LOP_IDENTITY_TYPE",
	160: "LOP_BEGIN_RECOVERY", 161: "LOP_END_RECOVERY", 162: "LOP_NONLOGGED_OP",
	170: "LOP_SORT_BEGIN", 171: "LOP_SORT_END", 172: "LOP_SORT_EXTENT",
	173: "LOP_CREATE_INDEX", 174: "LOP_DROP_INDEX", 175: "LOP_SORT_MEMORY",
	200: "LOP_REPL_COMMAND", 201: "LOP_BEGIN_UPDATE", 202: "LOP_END_UPDATE",
	203: "LOP_TEXT_POINTER", 204: "LOP_TEXT_INFO_BEGIN", 205: "LOP_TEXT_INFO_END",
	206: "LOP_REPL_NOOP", 207: "LOP_TEXT_VALUE", 211: "LOP_SHINK_NOOP", 221: "LOP_INVALIDATE_CACHE",
}

// 0->7 heap & index
// 8->14 allocation & space management
// 15->17 versioning & spapshot isolation
// 18->21 system catalogs & metadata
// 22->25 transaction & log management
//26-27 filestream
//28->31 recovery & repair

var ContextType = map[uint8]string{
	0: "LCX_NULL", 1: "LCX_HEAP", 2: "LCX_CLUSTERED",
	3: "LCX_INDEX_LEAF", 4: "LCX_INDEX_INTERIOR",
	5: "LCX_TEXT_MIX", 6: "LCX_TEXT_TREE", 7: "LCX_TEXT_ROOT",
	8: "LCX_PFS", 9: "LCX_GAM",
	11: "LCX_IAM", 12: "LCX_BOO_PAGE", 13: "LCX_DIFF_MAP",
	14: "LCX_BULK_OPERATION",
	15: "LCX_VERSION_STORE", 16: "LCX_VERSIONING_INFO",
	17: "LCX_SNAPSHOT",
	18: "LCX_SYSTEM_TABLE", 19: "LCX_METADATA", 20: "LCX_SERVICE_BROKER",
	21: "LCX_SECURITY",
	22: "LCX_LOCK_MANAGER", 23: "LCX_TRANSACTION_MANAGER", 24: "LCX_XACT",
	25: "LCX_LOG_MANAGER",
	26: "LCX_FILESTREAM_DATA", 27: "LCX_FILESTREAM_METADATA",
}
