// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: comms.proto

package mssqlparser_comms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileProcessor_Process_FullMethodName          = "/FileProcessor/Process"
	FileProcessor_ProcessMTF_FullMethodName       = "/FileProcessor/ProcessMTF"
	FileProcessor_GetTableContents_FullMethodName = "/FileProcessor/GetTableContents"
)

// FileProcessorClient is the client API for FileProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileProcessorClient interface {
	Process(ctx context.Context, in *FileDetails, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Table], error)
	ProcessMTF(ctx context.Context, in *MTFDetails, opts ...grpc.CallOption) (*Tables, error)
	GetTableContents(ctx context.Context, in *Table, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Row], error)
}

type fileProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewFileProcessorClient(cc grpc.ClientConnInterface) FileProcessorClient {
	return &fileProcessorClient{cc}
}

func (c *fileProcessorClient) Process(ctx context.Context, in *FileDetails, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Table], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileProcessor_ServiceDesc.Streams[0], FileProcessor_Process_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileDetails, Table]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessor_ProcessClient = grpc.ServerStreamingClient[Table]

func (c *fileProcessorClient) ProcessMTF(ctx context.Context, in *MTFDetails, opts ...grpc.CallOption) (*Tables, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tables)
	err := c.cc.Invoke(ctx, FileProcessor_ProcessMTF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessorClient) GetTableContents(ctx context.Context, in *Table, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Row], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileProcessor_ServiceDesc.Streams[1], FileProcessor_GetTableContents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Table, Row]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessor_GetTableContentsClient = grpc.ServerStreamingClient[Row]

// FileProcessorServer is the server API for FileProcessor service.
// All implementations must embed UnimplementedFileProcessorServer
// for forward compatibility.
type FileProcessorServer interface {
	Process(*FileDetails, grpc.ServerStreamingServer[Table]) error
	ProcessMTF(context.Context, *MTFDetails) (*Tables, error)
	GetTableContents(*Table, grpc.ServerStreamingServer[Row]) error
	mustEmbedUnimplementedFileProcessorServer()
}

// UnimplementedFileProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileProcessorServer struct{}

func (UnimplementedFileProcessorServer) Process(*FileDetails, grpc.ServerStreamingServer[Table]) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedFileProcessorServer) ProcessMTF(context.Context, *MTFDetails) (*Tables, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMTF not implemented")
}
func (UnimplementedFileProcessorServer) GetTableContents(*Table, grpc.ServerStreamingServer[Row]) error {
	return status.Errorf(codes.Unimplemented, "method GetTableContents not implemented")
}
func (UnimplementedFileProcessorServer) mustEmbedUnimplementedFileProcessorServer() {}
func (UnimplementedFileProcessorServer) testEmbeddedByValue()                       {}

// UnsafeFileProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileProcessorServer will
// result in compilation errors.
type UnsafeFileProcessorServer interface {
	mustEmbedUnimplementedFileProcessorServer()
}

func RegisterFileProcessorServer(s grpc.ServiceRegistrar, srv FileProcessorServer) {
	// If the following call pancis, it indicates UnimplementedFileProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileProcessor_ServiceDesc, srv)
}

func _FileProcessor_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDetails)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileProcessorServer).Process(m, &grpc.GenericServerStream[FileDetails, Table]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessor_ProcessServer = grpc.ServerStreamingServer[Table]

func _FileProcessor_ProcessMTF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MTFDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessorServer).ProcessMTF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileProcessor_ProcessMTF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessorServer).ProcessMTF(ctx, req.(*MTFDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessor_GetTableContents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Table)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileProcessorServer).GetTableContents(m, &grpc.GenericServerStream[Table, Row]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessor_GetTableContentsServer = grpc.ServerStreamingServer[Row]

// FileProcessor_ServiceDesc is the grpc.ServiceDesc for FileProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileProcessor",
	HandlerType: (*FileProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMTF",
			Handler:    _FileProcessor_ProcessMTF_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _FileProcessor_Process_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTableContents",
			Handler:       _FileProcessor_GetTableContents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "comms.proto",
}
