// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: comms.proto

package mssqlparser_comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mdffile       string                 `protobuf:"bytes,1,opt,name=Mdffile,proto3" json:"Mdffile,omitempty"`
	Ldffile       string                 `protobuf:"bytes,2,opt,name=Ldffile,proto3" json:"Ldffile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDetails) Reset() {
	*x = FileDetails{}
	mi := &file_comms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDetails) ProtoMessage() {}

func (x *FileDetails) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDetails.ProtoReflect.Descriptor instead.
func (*FileDetails) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{0}
}

func (x *FileDetails) GetMdffile() string {
	if x != nil {
		return x.Mdffile
	}
	return ""
}

func (x *FileDetails) GetLdffile() string {
	if x != nil {
		return x.Ldffile
	}
	return ""
}

type MTFDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MtfFile       string                 `protobuf:"bytes,1,opt,name=MtfFile,proto3" json:"MtfFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTFDetails) Reset() {
	*x = MTFDetails{}
	mi := &file_comms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTFDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTFDetails) ProtoMessage() {}

func (x *MTFDetails) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTFDetails.ProtoReflect.Descriptor instead.
func (*MTFDetails) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{1}
}

func (x *MTFDetails) GetMtfFile() string {
	if x != nil {
		return x.MtfFile
	}
	return ""
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_comms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TablesMSG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=Tables,proto3" json:"Tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TablesMSG) Reset() {
	*x = TablesMSG{}
	mi := &file_comms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TablesMSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablesMSG) ProtoMessage() {}

func (x *TablesMSG) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablesMSG.ProtoReflect.Descriptor instead.
func (*TablesMSG) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{3}
}

func (x *TablesMSG) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_comms_proto protoreflect.FileDescriptor

var file_comms_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x64, 0x66, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x64, 0x66, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x64, 0x66, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x64, 0x66, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0x26, 0x0a, 0x0a, 0x4d, 0x54, 0x46, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x74, 0x66, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x74, 0x66, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x4d,
	0x53, 0x47, 0x12, 0x1e, 0x0a, 0x06, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x06, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x32, 0x5d, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0c,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x06, 0x2e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x27, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x4d, 0x54, 0x46, 0x12, 0x0b, 0x2e, 0x4d, 0x54, 0x46, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x1a, 0x0a, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x4d, 0x53, 0x47, 0x22,
	0x00, 0x42, 0x13, 0x5a, 0x11, 0x6d, 0x73, 0x73, 0x71, 0x6c, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_comms_proto_rawDescOnce sync.Once
	file_comms_proto_rawDescData []byte
)

func file_comms_proto_rawDescGZIP() []byte {
	file_comms_proto_rawDescOnce.Do(func() {
		file_comms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)))
	})
	return file_comms_proto_rawDescData
}

var file_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_comms_proto_goTypes = []any{
	(*FileDetails)(nil), // 0: FileDetails
	(*MTFDetails)(nil),  // 1: MTFDetails
	(*Table)(nil),       // 2: Table
	(*TablesMSG)(nil),   // 3: TablesMSG
}
var file_comms_proto_depIdxs = []int32{
	2, // 0: TablesMSG.Tables:type_name -> Table
	0, // 1: FileProcessor.Process:input_type -> FileDetails
	1, // 2: FileProcessor.ProcessMTF:input_type -> MTFDetails
	2, // 3: FileProcessor.Process:output_type -> Table
	3, // 4: FileProcessor.ProcessMTF:output_type -> TablesMSG
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_comms_proto_init() }
func file_comms_proto_init() {
	if File_comms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comms_proto_goTypes,
		DependencyIndexes: file_comms_proto_depIdxs,
		MessageInfos:      file_comms_proto_msgTypes,
	}.Build()
	File_comms_proto = out.File
	file_comms_proto_goTypes = nil
	file_comms_proto_depIdxs = nil
}
