// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: comms.proto

package mssqlparser_comms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileProcessorService_Process_FullMethodName                = "/FileProcessorService/Process"
	FileProcessorService_ProcessMTF_FullMethodName             = "/FileProcessorService/ProcessMTF"
	FileProcessorService_ExportTable_FullMethodName            = "/FileProcessorService/ExportTable"
	FileProcessorService_GetTableContents_FullMethodName       = "/FileProcessorService/GetTableContents"
	FileProcessorService_GetTableAllocationInfo_FullMethodName = "/FileProcessorService/GetTableAllocationInfo"
	FileProcessorService_MessageStream_FullMethodName          = "/FileProcessorService/MessageStream"
)

// FileProcessorServiceClient is the client API for FileProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileProcessorServiceClient interface {
	Process(ctx context.Context, in *FileDetails, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TableResponse], error)
	ProcessMTF(ctx context.Context, in *MTFDetails, opts ...grpc.CallOption) (*Tables, error)
	ExportTable(ctx context.Context, in *Table, opts ...grpc.CallOption) (*Message, error)
	GetTableContents(ctx context.Context, in *Table, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Row], error)
	GetTableAllocationInfo(ctx context.Context, in *Table, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Page], error)
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, Message], error)
}

type fileProcessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileProcessorServiceClient(cc grpc.ClientConnInterface) FileProcessorServiceClient {
	return &fileProcessorServiceClient{cc}
}

func (c *fileProcessorServiceClient) Process(ctx context.Context, in *FileDetails, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TableResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileProcessorService_ServiceDesc.Streams[0], FileProcessorService_Process_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileDetails, TableResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_ProcessClient = grpc.ServerStreamingClient[TableResponse]

func (c *fileProcessorServiceClient) ProcessMTF(ctx context.Context, in *MTFDetails, opts ...grpc.CallOption) (*Tables, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tables)
	err := c.cc.Invoke(ctx, FileProcessorService_ProcessMTF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessorServiceClient) ExportTable(ctx context.Context, in *Table, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, FileProcessorService_ExportTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileProcessorServiceClient) GetTableContents(ctx context.Context, in *Table, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Row], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileProcessorService_ServiceDesc.Streams[1], FileProcessorService_GetTableContents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Table, Row]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_GetTableContentsClient = grpc.ServerStreamingClient[Row]

func (c *fileProcessorServiceClient) GetTableAllocationInfo(ctx context.Context, in *Table, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Page], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileProcessorService_ServiceDesc.Streams[2], FileProcessorService_GetTableAllocationInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Table, Page]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_GetTableAllocationInfoClient = grpc.ServerStreamingClient[Page]

func (c *fileProcessorServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileProcessorService_ServiceDesc.Streams[3], FileProcessorService_MessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_MessageStreamClient = grpc.ClientStreamingClient[Message, Message]

// FileProcessorServiceServer is the server API for FileProcessorService service.
// All implementations must embed UnimplementedFileProcessorServiceServer
// for forward compatibility.
type FileProcessorServiceServer interface {
	Process(*FileDetails, grpc.ServerStreamingServer[TableResponse]) error
	ProcessMTF(context.Context, *MTFDetails) (*Tables, error)
	ExportTable(context.Context, *Table) (*Message, error)
	GetTableContents(*Table, grpc.ServerStreamingServer[Row]) error
	GetTableAllocationInfo(*Table, grpc.ServerStreamingServer[Page]) error
	MessageStream(grpc.ClientStreamingServer[Message, Message]) error
	mustEmbedUnimplementedFileProcessorServiceServer()
}

// UnimplementedFileProcessorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileProcessorServiceServer struct{}

func (UnimplementedFileProcessorServiceServer) Process(*FileDetails, grpc.ServerStreamingServer[TableResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedFileProcessorServiceServer) ProcessMTF(context.Context, *MTFDetails) (*Tables, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMTF not implemented")
}
func (UnimplementedFileProcessorServiceServer) ExportTable(context.Context, *Table) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportTable not implemented")
}
func (UnimplementedFileProcessorServiceServer) GetTableContents(*Table, grpc.ServerStreamingServer[Row]) error {
	return status.Errorf(codes.Unimplemented, "method GetTableContents not implemented")
}
func (UnimplementedFileProcessorServiceServer) GetTableAllocationInfo(*Table, grpc.ServerStreamingServer[Page]) error {
	return status.Errorf(codes.Unimplemented, "method GetTableAllocationInfo not implemented")
}
func (UnimplementedFileProcessorServiceServer) MessageStream(grpc.ClientStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedFileProcessorServiceServer) mustEmbedUnimplementedFileProcessorServiceServer() {}
func (UnimplementedFileProcessorServiceServer) testEmbeddedByValue()                              {}

// UnsafeFileProcessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileProcessorServiceServer will
// result in compilation errors.
type UnsafeFileProcessorServiceServer interface {
	mustEmbedUnimplementedFileProcessorServiceServer()
}

func RegisterFileProcessorServiceServer(s grpc.ServiceRegistrar, srv FileProcessorServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileProcessorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileProcessorService_ServiceDesc, srv)
}

func _FileProcessorService_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDetails)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileProcessorServiceServer).Process(m, &grpc.GenericServerStream[FileDetails, TableResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_ProcessServer = grpc.ServerStreamingServer[TableResponse]

func _FileProcessorService_ProcessMTF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MTFDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessorServiceServer).ProcessMTF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileProcessorService_ProcessMTF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessorServiceServer).ProcessMTF(ctx, req.(*MTFDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessorService_ExportTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Table)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessorServiceServer).ExportTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileProcessorService_ExportTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessorServiceServer).ExportTable(ctx, req.(*Table))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileProcessorService_GetTableContents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Table)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileProcessorServiceServer).GetTableContents(m, &grpc.GenericServerStream[Table, Row]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_GetTableContentsServer = grpc.ServerStreamingServer[Row]

func _FileProcessorService_GetTableAllocationInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Table)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileProcessorServiceServer).GetTableAllocationInfo(m, &grpc.GenericServerStream[Table, Page]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_GetTableAllocationInfoServer = grpc.ServerStreamingServer[Page]

func _FileProcessorService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileProcessorServiceServer).MessageStream(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileProcessorService_MessageStreamServer = grpc.ClientStreamingServer[Message, Message]

// FileProcessorService_ServiceDesc is the grpc.ServiceDesc for FileProcessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileProcessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileProcessorService",
	HandlerType: (*FileProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMTF",
			Handler:    _FileProcessorService_ProcessMTF_Handler,
		},
		{
			MethodName: "ExportTable",
			Handler:    _FileProcessorService_ExportTable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _FileProcessorService_Process_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTableContents",
			Handler:       _FileProcessorService_GetTableContents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTableAllocationInfo",
			Handler:       _FileProcessorService_GetTableAllocationInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MessageStream",
			Handler:       _FileProcessorService_MessageStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "comms.proto",
}
