// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: comms.proto

package mssqlparser_comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mdffile       string                 `protobuf:"bytes,1,opt,name=Mdffile,proto3" json:"Mdffile,omitempty"`
	Ldffile       string                 `protobuf:"bytes,2,opt,name=Ldffile,proto3" json:"Ldffile,omitempty"`
	Carve         bool                   `protobuf:"varint,3,opt,name=Carve,proto3" json:"Carve,omitempty"`
	LdfLevel      uint32                 `protobuf:"varint,4,opt,name=LdfLevel,proto3" json:"LdfLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDetails) Reset() {
	*x = FileDetails{}
	mi := &file_comms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDetails) ProtoMessage() {}

func (x *FileDetails) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDetails.ProtoReflect.Descriptor instead.
func (*FileDetails) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{0}
}

func (x *FileDetails) GetMdffile() string {
	if x != nil {
		return x.Mdffile
	}
	return ""
}

func (x *FileDetails) GetLdffile() string {
	if x != nil {
		return x.Ldffile
	}
	return ""
}

func (x *FileDetails) GetCarve() bool {
	if x != nil {
		return x.Carve
	}
	return false
}

func (x *FileDetails) GetLdfLevel() uint32 {
	if x != nil {
		return x.LdfLevel
	}
	return 0
}

type MTF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MtfFile       string                 `protobuf:"bytes,1,opt,name=MtfFile,proto3" json:"MtfFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTF) Reset() {
	*x = MTF{}
	mi := &file_comms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTF) ProtoMessage() {}

func (x *MTF) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTF.ProtoReflect.Descriptor instead.
func (*MTF) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{1}
}

func (x *MTF) GetMtfFile() string {
	if x != nil {
		return x.MtfFile
	}
	return ""
}

type Col struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Col) Reset() {
	*x = Col{}
	mi := &file_comms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Col) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Col) ProtoMessage() {}

func (x *Col) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Col.ProtoReflect.Descriptor instead.
func (*Col) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{2}
}

func (x *Col) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Col) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	NofRows       uint32                 `protobuf:"varint,3,opt,name=NofRows,proto3" json:"NofRows,omitempty"`
	Cols          []*Col                 `protobuf:"bytes,4,rep,name=Cols,proto3" json:"Cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_comms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{3}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Table) GetNofRows() uint32 {
	if x != nil {
		return x.NofRows
	}
	return 0
}

func (x *Table) GetCols() []*Col {
	if x != nil {
		return x.Cols
	}
	return nil
}

type TableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*TableResponse_Table
	//	*TableResponse_Message
	MessageType   isTableResponse_MessageType `protobuf_oneof:"MessageType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableResponse) Reset() {
	*x = TableResponse{}
	mi := &file_comms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableResponse) ProtoMessage() {}

func (x *TableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableResponse.ProtoReflect.Descriptor instead.
func (*TableResponse) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{4}
}

func (x *TableResponse) GetMessageType() isTableResponse_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *TableResponse) GetTable() *Table {
	if x != nil {
		if x, ok := x.MessageType.(*TableResponse_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *TableResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.MessageType.(*TableResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isTableResponse_MessageType interface {
	isTableResponse_MessageType()
}

type TableResponse_Table struct {
	Table *Table `protobuf:"bytes,1,opt,name=Table,proto3,oneof"`
}

type TableResponse_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=Message,proto3,oneof"`
}

func (*TableResponse_Table) isTableResponse_MessageType() {}

func (*TableResponse_Message) isTableResponse_MessageType() {}

type Rows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []*Row                 `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rows) Reset() {
	*x = Rows{}
	mi := &file_comms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rows) ProtoMessage() {}

func (x *Rows) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rows.ProtoReflect.Descriptor instead.
func (*Rows) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{5}
}

func (x *Rows) GetRow() []*Row {
	if x != nil {
		return x.Row
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ExportPath    string                 `protobuf:"bytes,2,opt,name=ExportPath,proto3" json:"ExportPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_comms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{6}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetExportPath() string {
	if x != nil {
		return x.ExportPath
	}
	return ""
}

type RowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*RowResponse_Row
	//	*RowResponse_Message
	MessageType   isRowResponse_MessageType `protobuf_oneof:"MessageType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowResponse) Reset() {
	*x = RowResponse{}
	mi := &file_comms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowResponse) ProtoMessage() {}

func (x *RowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowResponse.ProtoReflect.Descriptor instead.
func (*RowResponse) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{7}
}

func (x *RowResponse) GetMessageType() isRowResponse_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *RowResponse) GetRow() *Row {
	if x != nil {
		if x, ok := x.MessageType.(*RowResponse_Row); ok {
			return x.Row
		}
	}
	return nil
}

func (x *RowResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.MessageType.(*RowResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isRowResponse_MessageType interface {
	isRowResponse_MessageType()
}

type RowResponse_Row struct {
	Row *Row `protobuf:"bytes,1,opt,name=Row,proto3,oneof"`
}

type RowResponse_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=Message,proto3,oneof"`
}

func (*RowResponse_Row) isRowResponse_MessageType() {}

func (*RowResponse_Message) isRowResponse_MessageType() {}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vals          []string               `protobuf:"bytes,1,rep,name=Vals,proto3" json:"Vals,omitempty"`
	Carved        bool                   `protobuf:"varint,2,opt,name=Carved,proto3" json:"Carved,omitempty"`
	Logged        bool                   `protobuf:"varint,3,opt,name=Logged,proto3" json:"Logged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_comms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{8}
}

func (x *Row) GetVals() []string {
	if x != nil {
		return x.Vals
	}
	return nil
}

func (x *Row) GetCarved() bool {
	if x != nil {
		return x.Carved
	}
	return false
}

func (x *Row) GetLogged() bool {
	if x != nil {
		return x.Logged
	}
	return false
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	ID            uint32                 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_comms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{9}
}

func (x *Page) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Page) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Tables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=Tables,proto3" json:"Tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tables) Reset() {
	*x = Tables{}
	mi := &file_comms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tables) ProtoMessage() {}

func (x *Tables) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tables.ProtoReflect.Descriptor instead.
func (*Tables) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{10}
}

func (x *Tables) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_comms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExporPath     string                 `protobuf:"bytes,1,opt,name=ExporPath,proto3" json:"ExporPath,omitempty"`
	Carve         bool                   `protobuf:"varint,2,opt,name=Carve,proto3" json:"Carve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_comms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{12}
}

func (x *Config) GetExporPath() string {
	if x != nil {
		return x.ExporPath
	}
	return ""
}

func (x *Config) GetCarve() bool {
	if x != nil {
		return x.Carve
	}
	return false
}

var File_comms_proto protoreflect.FileDescriptor

var file_comms_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x64, 0x66, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x64, 0x66, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x64, 0x66, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x64, 0x66, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x43, 0x61, 0x72, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x64, 0x66, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x4c, 0x64, 0x66, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x22, 0x1f, 0x0a, 0x03, 0x4d, 0x54, 0x46, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x74, 0x66,
	0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x74, 0x66, 0x46,
	0x69, 0x6c, 0x65, 0x22, 0x2d, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x63, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x66, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x4e, 0x6f, 0x66, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x18, 0x0a,
	0x04, 0x43, 0x6f, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x43, 0x6f,
	0x6c, 0x52, 0x04, 0x43, 0x6f, 0x6c, 0x73, 0x22, 0x64, 0x0a, 0x0d, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x48,
	0x00, 0x52, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0d,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1e, 0x0a,
	0x04, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x16, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x04, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x3e, 0x0a,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x5c, 0x0a,
	0x0b, 0x52, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x03,
	0x52, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x52, 0x6f, 0x77, 0x48,
	0x00, 0x52, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x0a, 0x0b,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x03, 0x52,
	0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x56, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x76, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x43, 0x61, 0x72, 0x76, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x49, 0x44, 0x22, 0x28, 0x0a, 0x06, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x06,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x06, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x3c, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x43, 0x61, 0x72, 0x76, 0x65, 0x32,
	0xfe, 0x02, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x07, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x08,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x07, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12,
	0x2b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0c, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x0e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x26, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x61, 0x6b, 0x12, 0x04, 0x2e, 0x4d, 0x54, 0x46,
	0x1a, 0x0e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x21, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x06, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x08, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x06, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x04,
	0x2e, 0x52, 0x6f, 0x77, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x06, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x05, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x13, 0x5a, 0x11, 0x6d, 0x73, 0x73, 0x71, 0x6c, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_comms_proto_rawDescOnce sync.Once
	file_comms_proto_rawDescData []byte
)

func file_comms_proto_rawDescGZIP() []byte {
	file_comms_proto_rawDescOnce.Do(func() {
		file_comms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)))
	})
	return file_comms_proto_rawDescData
}

var file_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_comms_proto_goTypes = []any{
	(*FileDetails)(nil),   // 0: FileDetails
	(*MTF)(nil),           // 1: MTF
	(*Col)(nil),           // 2: Col
	(*Table)(nil),         // 3: Table
	(*TableResponse)(nil), // 4: TableResponse
	(*Rows)(nil),          // 5: Rows
	(*Database)(nil),      // 6: Database
	(*RowResponse)(nil),   // 7: RowResponse
	(*Row)(nil),           // 8: Row
	(*Page)(nil),          // 9: Page
	(*Tables)(nil),        // 10: Tables
	(*Message)(nil),       // 11: Message
	(*Config)(nil),        // 12: Config
}
var file_comms_proto_depIdxs = []int32{
	2,  // 0: Table.Cols:type_name -> Col
	3,  // 1: TableResponse.Table:type_name -> Table
	11, // 2: TableResponse.Message:type_name -> Message
	8,  // 3: Rows.row:type_name -> Row
	8,  // 4: RowResponse.Row:type_name -> Row
	11, // 5: RowResponse.Message:type_name -> Message
	3,  // 6: Tables.Tables:type_name -> Table
	12, // 7: FileProcessorService.SetConfig:input_type -> Config
	12, // 8: FileProcessorService.UpdateConfig:input_type -> Config
	0,  // 9: FileProcessorService.Process:input_type -> FileDetails
	1,  // 10: FileProcessorService.ProcessBak:input_type -> MTF
	3,  // 11: FileProcessorService.ExportTable:input_type -> Table
	6,  // 12: FileProcessorService.ExportDatabase:input_type -> Database
	3,  // 13: FileProcessorService.GetTableContents:input_type -> Table
	3,  // 14: FileProcessorService.GetTableAllocationInfo:input_type -> Table
	11, // 15: FileProcessorService.MessageStream:input_type -> Message
	11, // 16: FileProcessorService.SetConfig:output_type -> Message
	11, // 17: FileProcessorService.UpdateConfig:output_type -> Message
	4,  // 18: FileProcessorService.Process:output_type -> TableResponse
	4,  // 19: FileProcessorService.ProcessBak:output_type -> TableResponse
	11, // 20: FileProcessorService.ExportTable:output_type -> Message
	11, // 21: FileProcessorService.ExportDatabase:output_type -> Message
	8,  // 22: FileProcessorService.GetTableContents:output_type -> Row
	9,  // 23: FileProcessorService.GetTableAllocationInfo:output_type -> Page
	11, // 24: FileProcessorService.MessageStream:output_type -> Message
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_comms_proto_init() }
func file_comms_proto_init() {
	if File_comms_proto != nil {
		return
	}
	file_comms_proto_msgTypes[4].OneofWrappers = []any{
		(*TableResponse_Table)(nil),
		(*TableResponse_Message)(nil),
	}
	file_comms_proto_msgTypes[7].OneofWrappers = []any{
		(*RowResponse_Row)(nil),
		(*RowResponse_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comms_proto_goTypes,
		DependencyIndexes: file_comms_proto_depIdxs,
		MessageInfos:      file_comms_proto_msgTypes,
	}.Build()
	File_comms_proto = out.File
	file_comms_proto_goTypes = nil
	file_comms_proto_depIdxs = nil
}
